repos:
  - repo: local
    hooks:
      - id: dart-format
        name: dart format
        entry: dart format
        language: system
        types: [dart]
        pass_filenames: true
      - id: app-artwork-mtime
        name: check app artwork mtimes
        entry: make check-app-artwork-mtime
        language: system
        files: ^(artwork/.*\.(svg|png|jpe?g)|apps/brick_timer/assets/.*\.(png|jpe?g))$
        pass_filenames: false
