// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1aaKQjSI_L28NS5axFCWqsk4SrXI1CEg',
    appId: '1:99422701171:web:5f13f9e15e939c25a70c06',
    messagingSenderId: '99422701171',
    projectId: 'bricktimer-bramp-net',
    authDomain: 'bricktimer-bramp-net.firebaseapp.com',
    storageBucket: 'bricktimer-bramp-net.firebasestorage.app',
    measurementId: 'G-9YH6CERR7K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGONZKwSlgKUyRq3lv5fD5n4YwqYmINJg',
    appId: '1:99422701171:android:1118268157e06a92a70c06',
    messagingSenderId: '99422701171',
    projectId: 'bricktimer-bramp-net',
    storageBucket: 'bricktimer-bramp-net.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZLJ3_MWf2iRIWyP4toXJdExh9wthWjvA',
    appId: '1:99422701171:ios:6562b0167d980c37a70c06',
    messagingSenderId: '99422701171',
    projectId: 'bricktimer-bramp-net',
    storageBucket: 'bricktimer-bramp-net.firebasestorage.app',
    iosBundleId: 'net.bramp.bricktimer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZLJ3_MWf2iRIWyP4toXJdExh9wthWjvA',
    appId: '1:99422701171:ios:6562b0167d980c37a70c06',
    messagingSenderId: '99422701171',
    projectId: 'bricktimer-bramp-net',
    storageBucket: 'bricktimer-bramp-net.firebasestorage.app',
    iosBundleId: 'net.bramp.bricktimer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1aaKQjSI_L28NS5axFCWqsk4SrXI1CEg',
    appId: '1:99422701171:web:982bb7c24d06f756a70c06',
    messagingSenderId: '99422701171',
    projectId: 'bricktimer-bramp-net',
    authDomain: 'bricktimer-bramp-net.firebaseapp.com',
    storageBucket: 'bricktimer-bramp-net.firebasestorage.app',
    measurementId: 'G-8R5EBXEE7F',
  );
}
