# Flutter Test Workflow Template
name: Test

on:
  workflow_call:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-go@v6
        with:
          go-version: stable
          cache: false

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
          pub-cache: true

      - name: Install dependencies
        run: make deps

      - name: Check generated app assets
        run: make check-assets

      - name: Check formatting
        run: make format && git diff --exit-code

      - name: Static analysis
        run: make lint

      - name: Run unit tests
        run: make test-unit-ci

  integration:
    runs-on: macos-latest
    needs: checks

    steps:
      - uses: actions/checkout@v6

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
          pub-cache: true

      - name: Install dependencies
        run: make deps

      - name: Run integration tests
        run: make test-integration-ci TEST_DEVICE=macos
