# Flutter Test Workflow Template
name: Test

on:
  workflow_call:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: stable

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Check generated app assets
        run: make check-assets
        continue-on-error: true

      - name: Check formatting
        run: make format && git diff --exit-code
        continue-on-error: true

      - name: Static analysis
        run: make analyze
        continue-on-error: true

      - name: Run tests
        run: make test-ci
